#!/bin/bash
set -e

PACKAGE_VERSION=$(sed -nE 's/Version: (.*?)/\1/p' DESCRIPTION)
echo Add version tag using $PACKAGE_VERSION

docker tag $IMAGE_NAME $DOCKER_REPO:$PACKAGE_VERSION
docker push $DOCKER_REPO:$PACKAGE_VERSION
